# .github/workflows/pacman.yml
name: Generate Pacman animation

on:
  workflow_dispatch:          # run manually
  push:                       # or on every push to main
    branches: [main]
  schedule:
    - cron: "0 */12 * * *"    # every 12 h at hh:00

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate SVG
        uses: abozanona/pacman-contribution-graph@v1
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
